### PR TITLE
Add more (optional) output data as requested

### PR DESCRIPTION
**Pull request by bgruening**
by our users! Users, Users, Users!

### CODE REVIEW

**Comment by bgruening** [comment]
I need to work on this ... sorry. Will talk to you about this tm. Don't release yet :)

**Comment by dpryan79** [comment]
No worries!

**Comment by dpryan79** [comment]
@bgruening Let me know if you have anything else planned. All of the current 2.2 milestones are complete and I'm just waiting to ensure that #305 doesn't require anything else. If you're done with your changes then I'll then get the next release started.

**Comment by dpryan79** [comment]
Ah, it'll ideally happen tuesday afternoon, since Fidel is pretty much booked until then

**Pull request merged**
