### PR TITLE
Docs and PEfragsize

### PR DESCRIPTION
**Pull request by vivekbhr**
1. bamPEFragSize goes "multi" (solving #341 ).. It simply loops over multiple BAMs and stores data in dict, then makes overlapping histogram like the one attached below.

2. Galaxy changes for bamPEfragsize.. @bgruening have a look. 

3. DOC changes : for bamPEfragsize + citations + other stuff. 

4. Deleted old README.txt and moved to .rst version of the README.md (latest).

** Travis happy except for one error I couldn't figure out.

```
1.49s$ if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then /home/travis/build/fidelram/deepTools/foo/bin/planemo lint galaxy/wrapper/ ; fi
Error loading tool with path /home/travis/build/fidelram/deepTools/galaxy/wrapper/bamPEFragmentSize.xml
Traceback (most recent call last):
  File "/home/travis/build/fidelram/deepTools/foo/local/lib/python2.7/site-packages/galaxy/tools/loader_directory.py", line 107, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
ParseError: mismatched tag: line 68, column 6
```
examplefragmentsize

### CODE REVIEW

**Comment by dpryan79** [comment]
I should have just fixed the Galaxy wrapper, you just omitted a closing tag. Can you test to ensure that the changes I made regarding setting limits (`--maxFragmentLength`) and using a log scale (`--logScale`) still work before merging?

**Comment by dpryan79** [comment]
Right, the text output is now different, which breaks Galaxy's tests again. If the current output is correct then either update the test output or let me know and I'll do it.

**Comment by vivekbhr** [comment]
yah I changed the test to include 2 bam files in place of one.. I will try tomorrow to fix this, and surrender to you if it doesn't work.

I have already tested --maxFragmentLength, will test --logScale tomorrow.

**Comment by vivekbhr** [comment]
I tested the commands --maxFragmentLength and --logScale, but still haven't done anything regarding test.. WIP WIP WIP..

**Comment by dpryan79** [comment]
The test should pass after my last commit. We don't need to wait for OSX to finish, travis has all OSX jobs stopped at the moment.

**Comment by dpryan79** [comment]
The bamPEFragmentSize Galaxy test is now passing.

**Comment by vivekbhr** [comment]
@dpryan79 :+1:

**Pull request merged**
