### PR TITLE
Plot the weights, not the projections!

### PR DESCRIPTION
**Pull request by dpryan79**
This fixes plotPCA

### CODE REVIEW

**Comment by bgruening** [comment]
Uh, good one!

**Comment by bgruening** [comment]
xref: https://github.com/fidelram/deepTools/compare/release-1.6...fix_PCA?expand=1
@fidelram should this go in before release?

**Comment by dpryan79** [comment]
@bgruening: Fidel's changes are no longer needed AFAIK.

**Comment by bgruening** [comment]
Ok, just double checking there was a lot of other stuff in this branch.

**Pull request merged**
