### PR TITLE
Wrapper fixes

### PR DESCRIPTION
**Pull request by dpryan79**
It turns out that any of the wrappers with a "Background" section were rendering incorrectly. For some reason, the "Background" section kept getting rendered at the top of the page!?!

I have no clue why this was happening, it's presumably a bug in how Galaxy renders things.

### CODE REVIEW

**Comment by dpryan79** [comment]
The affected wrappers are `computeGCBias`, `plotCorrelation`, `plotFingerprint`, and `plotPCA`.

**Comment by bgruening** [comment]
I fixed one of those yesterday: https://github.com/fidelram/deepTools/commit/e907472e6c8092c334c1d664a6891e01603f6a67

This is because titles are converted to div ids and these are overlapping with a Galaxy div ID that is called background. We have discussed to prefix all internal tool IDs with `_` or similar.

**Comment by dpryan79** [comment]
Ah, that explains why that one was fixed when I installed it locally :)

I just copied the title changes over to the other tools

**Comment by bgruening** [comment]
Magic! Sorry was to lazy to grep for other occurrences, I should have done so.

**Comment by dpryan79** [comment]
No worries, I'll merge this once Travis is happy. Could you then update the other 3 wrappers in the toolshed?

**Comment by bgruening** [comment]
Sure I have an other feature request for the wrappers I'm working on that I wanted to include once tested and then I will upadate everything

**Comment by dpryan79** [comment]
Sounds like a good plan!

**Pull request merged**
