### PR TITLE
WIP: bamCompare: removed reference to correlation calculation

### PR DESCRIPTION
**Pull request by thomasmanke**

### CODE REVIEW

**Comment by bgruening** [comment]
@thomasmanke I though you wanted to rename the tool :)

**Comment by dpryan79** [comment]
@bgruening Not when we need to get this thing partially out the door in the next couple days!

**Comment by thomasmanke** [comment]
Yes, I was very much in favour of changing the name, but I was overruled by people who actually know what they are doing. But it is high on the agenda (January)

**Comment by bgruening** [comment]
Ok, then lets merge this after all tests are passed :)

**Comment by vivekbhr** [comment]
All tests green.. :+1:

**Comment by bgruening** [comment]
I like green!

**Comment by fidelram** [comment]
I am not sure that Thomas was done ...

**Pull request merged**
