### PR TITLE
NFS empty file fix

### PR DESCRIPTION
**Pull request by bgruening**
This hopefully will close all open file handles which is essential on slow file systems like NFS. Otherwise the file will stay empty in Galaxy.

### CODE REVIEW

**Comment by bgruening** [comment]
Lessens learnt don't fix this with your cellphone without pep8 linting ;)
I got PR #300!!!!

**Comment by fidelram** [comment]
I will try to close always from now on

**Comment by dpryan79** [comment]
Hopefully this solves the issue.

**Comment by dpryan79** [comment]
BTW, I'm amazed that we've never run into this, since all of our mounts are via NFS.

**Comment by bgruening** [comment]
Thanks for merging!

**Comment by dpryan79** [comment]
This is an important enough fix that I'll bump #237 to version 2.3, since the other things for the 2.2 milestone are essentially already done.

**Pull request merged**
