### PR TITLE
activate hclust (optional)

### PR DESCRIPTION
**Pull request by vivekbhr**
fixed a minor conversion issue.
Activated hirarchichal clustering. but this added --hclust option in parserCommon. @bgruening 
The option can be removed/commented if we are not ready for it..

### CODE REVIEW

**Comment by bgruening** [comment]
Looks good to me, noted the argument change :)

**Comment by vivekbhr** [comment]
I just added something. In case of clusters with zero regions, the clustered output can still be used for plotting. So Instead of throwing the error, heatmapper will write the cluster output back.

**Comment by bgruening** [comment]
@vivekbhr can you please rebase this branch. Let me know if you need help to do this.

**Comment by vivekbhr** [comment]
@bgruening You mean rebase this with release-1.6 branch ?

**Comment by bgruening** [comment]
Yes exactly, it's not mergeable and travis will test your changes :)
So we see if we broke something :)

**Comment by vivekbhr** [comment]
My rebase is failing due to conflicts.. Now fidel asked me to wait since he's making some other change.

**Comment by fidelram** [comment]
I am just going to move vivek's changes into a new branch. Otherwise the pep8 changes and the changes from vivek are too dificult to merge.

**Pull request closed without merging**
