### PR TITLE
Doc and galaxy page changes

### PR DESCRIPTION
**Pull request by vivekbhr**
I am adding documentation changes in tools/rst and galaxy XML pages here..

### CODE REVIEW

**Comment by bgruening** [comment]
Can we change the title from the bamFP_test plot?

**Comment by vivekbhr** [comment]
@bgruening to?

**Comment by bgruening** [comment]
Something without test :) BAMFingerprint for example?

**Comment by vivekbhr** [comment]
Ok so I added these changes:
Better bam fingerprint example.
updated broken links in xml.
edited xml for plotcorrelation (plotType was showing wrong options).

I will make more doc changes after the merge..

**Comment by vivekbhr** [comment]
Just adding that the "plot title" is somehow not working for plotCorrelate at this moment..

**Comment by bgruening** [comment]
@vivekbhr in Galaxy or in general?
Thanks!

**Comment by vivekbhr** [comment]
@bgruening on galaxy.. works on CLI

**Comment by fidelram** [comment]
We need to fix all the urls pointing to: https://github.com/fidelram/deepTools/wiki/ there are 10 cases

```
galaxy/wrapper/correctGCBias.xml
galaxy/wrapper/bamCorrelate.xml
galaxy/wrapper/bamCoverage.xml
galaxy/wrapper/computeGCBias.xml
galaxy/wrapper/plotHeatmap.xml
galaxy/wrapper/bamFingerprint.xml
galaxy/wrapper/computeMatrix.xml
galaxy/wrapper/plotProfiler.xml
galaxy/wrapper/bamCompare.xml
```

**Comment by vivekbhr** [comment]
@fidelram okey. I can do that :+1:

**Comment by bgruening** [comment]
@vivekbhr plotTitle should be fixed with https://github.com/fidelram/deepTools/commit/ec44cb3e43858dff1c142d57ea9ca64339af996e
Thanks a bunch for catching this!

**Pull request merged**
