### PR TITLE
rst footer added

### PR DESCRIPTION
**Pull request by vivekbhr**
added a footer with links in rst pages.
@friedue if there's anything else let me know, or I'll take off the WIP..

### CODE REVIEW

**Comment by friedue** [comment]
looks good! but I'd reject the change to the British "ou" in neighbor --> we've been more or less sticking to the American spelling of things

**Comment by vivekbhr** [comment]
@friedue ok..

**Comment by dpryan79** [comment]
@vivekbhr I took the liberty of setting a max width of 600px on everything (I scaled the height correctly to match). This seems to render correctly on the test server. Unless you have other changes to make I would propose removing WIP and merging.

**Comment by vivekbhr** [comment]
@dpryan79 It's all looking good, except one example image was missing in multiBamSum so I remove the reference there (wasn't needed anyway).. Feel free to merge after it's all green.

**Pull request merged**
