### PR TITLE
Fabian dev

### PR DESCRIPTION
**Pull request by kilpert**
Some documentation

### CODE REVIEW

**Comment by dpryan79** [comment]
@kilpert: I'm adding the "WIP" label for "Work in progress". If this is ready to get merged then just remove it :)

**Comment by dpryan79** [comment]
@friedue: Just a heads up that Fabian is updating some documentation too :)

**Comment by friedue** [comment]
yeah, that was commissioned work ;)

**Comment by dpryan79** [comment]
:+1: from me either way!

**Comment by dpryan79** [comment]
Nice job @kilpert !

**Pull request merged**
